[profile.default]
solc_version = '0.8.16'
fs_permissions = [{ access = "read-write", path = "./deployments"}]
gas_reports = ["PWNSimpleLoan"]
evm_version = "paris"

[profile.default.fuzz]
  max_test_rejects = 1_000_000 # Number of times `vm.assume` can fail
  runs = 503


[rpc_endpoints]
# Mainnets
mainnet = "${ETHEREUM_URL}"
polygon = "${POLYGON_URL}"
arbitrum = "${ARBITRUM_URL}"
optimism = "${OPTIMISM_URL}"
base = "${BASE_URL}"
bsc = "${BSC_URL}"

# Testnets
sepolia = "${SEPOLIA_URL}"
goerli = "${GOERLI_URL}"
base_goerli = "${BASE_GOERLI_URL}"

tenderly = "${TENDERLY_URL}"
local = "${LOCAL_URL}"
